sudo: false
language: node_js
node_js:
- 12
branches:
  only:
  - master
install:
- npm install
cache:
  directories:
  - node_modules
dist: trusty
deploy:
  provider: heroku
  app: conflict-game
  api_key:
    secure: C+Dcx26kx9caIPpUWZG5N1wLrLOnbegja7gJxPHW6J9iqxBHMIfZEa3+cR1EF7nfRGlaRvkw8WSpUgb9bZxXyPyMafBb9035Od/K2Sv7+Y5kJigX8+DtWDqdFOuNGYy5wVhPUExliWcfSaZqET6P5MCOy2C8hsh+d/6XcKhFy36rPnW88oJTfkkWxS5+IFM9APv8N3GrX1zoWJ56UflNS0oVyGCNL32xP807rb+MndFaksW3cypHgkMxJIYrbJ92/MiT6NkvFq5v6VHIVL6IQeh7CO6DgfCMaXkdHJpkhli2V/xEAmfbEFRbgp5brj1b74rCiXLSIJS7fyl/1gaZT0hgiIQIuj1QkOd8ko0OQ33GWIOV11Z7CD4cMzWDiLtulKDeRblnfCBzxVXzgklWkGGi1tUf9NO+ZyWgDJDfE/kaFlWNjUvN7KxQn+wTJP85yIikdkoJzJjldvRH+1yKpmzpXMLf44fe4RotG9Vw11UGXV81jZofLjL+rvgAMqaVQ73N0SSYmE2I2R18ZdeyrF0eHvV/MHPF/Oq2kPZcgj1honBFLbcv3HqNyRdYX/8fO4FAoqr7RE39Y+n8LZtpXZB8EwJpCNNizjy84xzEdMZMvr9eWtPvbXHDRbpl9dbxjwOU4eUE8Cv+C5PaBeSHBABtS89HNWgZsRz3ltJ1ZGM=
